project:
  type: website
  output-dir: docs

website:
  title: "AMAR"
  navbar:
    background: maroon
    foreground: white
    left:
      - href: index.qmd
        text: "AMAR"
      - href: https://johannabirnir.com/data.html
        text: Other data projects
      - href: https://johannabirnir.com/ 
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

