---
title: ""
---

This is the AMAR (All Minorities at Risk) webpage. AMAR is an independent continuation of the Minorities at Risk (MAR) data that Ted Gurr began collecting in the 1980s about the political trajectories of minorities engaging the state worldwide.

On this page you can find links to publications outlining the structure and purpose of the AMAR data. There are also links to the data produced in the project and a link to the site of the original MAR (Minorities at Risk) data. Information on this page appears in reverse order with the latest first.

# AMAR and Natural Language Processing (NLP)

Our most recent efforts in the AMAR data collection aim to develop the most appropriate method for using NLP in coding of the data. This is ongoing work. The first article outlining our efforts at binary coding is:

Overos, Hlatky, Pathak, Goers, Gouws-Dewar, Smith, Chew, Birnir and Liu [Coding with the machines: machine-assisted coding of rare event data.](https://academic.oup.com/pnasnexus/article/3/5/pgae165/7659908) 2024. *PNAS Nexus.* 3(5):165.

- [Replication files](https://github.com/jkbirnir/Coding_with_the_machines)

**COMING SOON.** Our current work (Pathak and Birnir, with a number of students) aims to develop a method to go beyond binary coding of AMAR data with the objective of updating the AMAR data and filling in information for missing groups from the AMAR sample frame.

# The AMAR (All-Minorities at Risk) data

These are the 2 articles that outline the purpose and format of the AMAR data.

If you are looking to use the data please cite:

Jóhanna Birnir; David Laitin; Jonathan Wilkenfeld; David Waguespack; Agatha Hultquist; Ted Gurr. [Introducing the AMAR (All Minorities at Risk Data.](https://journals.sagepub.com/doi/full/10.1177/0022002717719974) 2018. *Journal of Conflict Resolution.* 62(1):203-226.

The replication data files are available [here.](https://www.dropbox.com/sh/g30wur1u0g8bppt/AAA01uvF4hEwYs8OU11wtnbea?dl=0)

If you are looking to use the group lists please cite:

Jóhanna Birnir, Jonathan Wilkenfeld, James Fearon, David Laitin, Ted Gurr, Stephen Saideman, Dawn Brancati, Amy Pate and Agatha Hultquist. [Socially Relevant Ethnic Groups, Ethnic Structure and AMAR.](https://journals.sagepub.com/doi/full/10.1177/0022343314536915) 2015. *Journal of Peace Research.* 52:105-109.

The group lists is available [here.](files/amar_ethnic_groups_list_january_2015.xls)

The AMAR codebook v1 is available [here.](files/AMAR%20Phase1Codebook.FINAL.1.web.Aug232016.pdf)

# The original MAR (Minorities at Risk) data

This is the [website](http://www.mar.umd.edu/mar_data.asp) where you can find the original MAR data and Codebooks along with some qualitative accounts of the minority groups.
